Improve authentication & networking layer
inputlogic/next-starter pull request #16
Opened 2024-03-12 16:11 UTC by derekcsm

- use Axios to replace api.js
- use middleware to replace auth-wrapper
- update iron-session
- updte page structure for determining authed state more simply
- add optional typescript support

2024-03-12 17:53 UTC, adriaanwm requested changes

2024-03-12 17:53 UTC, adriaanwm commented on components/modals/forgot-password-modal.js
> +      // await post('forgotPassword', data)
should this be replaced with something?

2024-03-12 17:53 UTC, adriaanwm commented on components/layouts/index.js
> +  console.log('layouts', layouts)
🧹

2024-03-12 17:53 UTC, adriaanwm commented on util/axiosClient.ts
> +)
what's the point of this response interceptor? I think there should be a comment here explaining why we're wrapping the error in Promise.reject .

2024-03-12 17:53 UTC, adriaanwm commented on util/axiosClient.ts
> +      console.log('urlPath', urlPath)
🧹

2024-03-12 17:53 UTC, adriaanwm commented on util/axiosClient.ts
> +        console.log('starts with /public', urlPath)
🧹

2024-03-12 17:53 UTC, adriaanwm commented on util/axiosClient.ts
> +const axiosClient = axios.create({
can we `export const axiosClient` rather than `export default axiosClient` ? I'd rather if we use named exports across the board and always avoid default exports. Not a big deal just trying to have consistency.

2024-03-12 17:53 UTC, adriaanwm commented on pages/index.js
> +          {/* <button onClick={() => logoutUserMutation.mutate()}>Logout</button> */}
can we get logout back?

2024-03-12 17:53 UTC, adriaanwm commented on pages/index.js
> +import { getUser } from 'hooks/getUser'
getUser should live in hooks anymore since it's not a hook 😄

2024-03-12 17:53 UTC, adriaanwm commented on pages/index.js
> +  } = useQuery({ queryKey: ['userProfile'], getUser })
Curious to know others thoughts on using `useQuery` directly in a component. We would normally create a hook in the hooks folder and just call the query (eg. useUser) in the component.

This will only apply in rare circumstances anyways, since most requests will use stencil where it will be:

`stencil.useQuery({path: '/user/my-profile'})`

2024-03-12 17:53 UTC, adriaanwm commented on pages/index.js
> +  } = useQuery({ queryKey: ['userProfile'], getUser })
Also, we have a pattern of hooks returning `[themainthing, reactQueryObj] ` instead of just returning `reactQueryObj`, It's nice for things like list requests since themainthing is actually reactQueryObj.data.results and we don't need to manually unpack it. eg.

```
const [posts, {isLoading}] = stencil.useQuery({path: '/user/posts'})
```

Any major objections to keeping this pattern?

2024-03-12 17:53 UTC, adriaanwm commented on pages/api/session.ts
> +  const session = await getIronSession<SessionData>(req, res, sessionOptions)
why are we getting the session here and never using it?

2024-03-12 17:53 UTC, adriaanwm commented on pages/index.js
> +      {userProfile && !userIsLoading && <p>Hello {userProfile?.firstName}</p>}
When I go to the root url http://localhost:3000/ and I'm logged in, I still see a log in button. I should see a my account link instead.

2024-03-12 18:36 UTC, derekcsm commented on components/modals/forgot-password-modal.js
> +      // await post('forgotPassword', data)
TODO for now, will do in a bit! just need to add a forgotPassword request

2024-03-12 18:36 UTC, derekcsm commented on util/ironSession.ts
> +}
removed, was for testing

2024-03-12 18:37 UTC, derekcsm commented on pages/index.js
> +      {userProfile && !userIsLoading && <p>Hello {userProfile?.firstName}</p>}
ah right you shouldn't be able to visit that url when you're logged in, will fix

2024-03-12 18:41 UTC, derekcsm commented on pages/api/session.ts
> +  const session = await getIronSession<SessionData>(req, res, sessionOptions)
good catch, fixed

2024-03-12 19:11 UTC, derekcsm commented on pages/index.js
> +import { getUser } from 'hooks/getUser'
what should the folder be for these? maybe _api top level folder

2024-03-12 19:48 UTC, derekcsm commented on pages/index.js
> +  } = useQuery({ queryKey: ['userProfile'], getUser })
made getUser a hook but the question is still relevant. Idk if it makes sense for all requests to be hooks, for mutate requests idk what the benefit would be, get requests make sense for sure

2024-03-13 01:15 UTC, adriaanwm requested changes
It looks like I'm getting a 500 error on login failure for any status code from the django api. For example if the api returns a 404 then the node endpoint is returning a 500. I'd rather if it passes along the same error code and message as the django api

2024-03-13 01:15 UTC, adriaanwm commented on pages/index.js
> +import { getUser } from 'hooks/getUser'
could be, I'd lean towards hiding them in utils/api or something just cause I find the root of project is already noisy enough 😄

2024-03-13 01:15 UTC, adriaanwm commented on pages/index.js
> +  } = useQuery({ queryKey: ['userProfile'], getUser })
yeah I kind of agree in that that's why I like stencil 😅 , creating all the mutations as functions is tedious and can be repetitive.

2024-03-13 01:19 UTC, adriaanwm requested changes
I'd like the middleware to be updated so both authed/unauthed users can see the landing page `/` , and the only difference should be whether there's a `login` button or account related buttons in the header.

So essentially we will have:
- auth only routes (eg. account dashboard)
- public only routes (eg. if there were a login page)
- auth & public routes (eg. landing)

2024-03-18 13:38 UTC, adriaanwm approved these changes
Nice work! I would like one more set of eyes on this before we merge.

2024-03-18 13:38 UTC, adriaanwm commented on hooks/session.ts
> +export const getBasicSession = async (): Promise<BasicSessionData> => {
I'm not convinced this gives us any real benefit. Is the idea that if there is malicious javascript on our website, it will have a harder time finding the token if we mostly use getBasicSession, and only use getSession in the axios interceptor?

2024-03-18 13:40 UTC, adriaanwm commented on util/axiosClient.ts
> +      console.log('config.url', config.url)
🧹

2024-03-18 13:40 UTC, adriaanwm commented on util/axiosClient.ts
> +      console.log('urlPath', urlPath)
🧹

2024-03-18 13:40 UTC, adriaanwm commented on util/axiosClient.ts
> +        console.log('Adding token to request')
🧹

2024-03-18 13:45 UTC, adriaanwm commented on hooks/session.ts
> +export const getBasicSession = async (): Promise<BasicSessionData> => {
I am malicious javascript 👿 and I want the token, this is the code I inject:
```
const originalOpen = XMLHttpRequest.prototype.open;

XMLHttpRequest.prototype.open = function() {
  this.addEventListener('load', function() {
    try {
      const response = JSON.parse(this.responseText);
      if(response.hasOwnProperty('token')) {
        console.log('Token found in response:', response.token);
      }
    } catch(e) {
      // Not JSON response or other parsing error
    }
  });

  originalOpen.apply(this, arguments);
};
```

2024-03-18 16:25 UTC, derekcsm commented on hooks/session.ts
> +export const getBasicSession = async (): Promise<BasicSessionData> => {
yeah true, I guess it's more of my paranoia than real security. But it is _some_ level of obscurity I guess

2024-03-18 16:29 UTC, derekcsm commented on hooks/session.ts
> +export const getBasicSession = async (): Promise<BasicSessionData> => {
how can we prevent against that attack though? 🤔

2024-03-18 16:46 UTC, derekcsm commented on hooks/session.ts
> +export const getBasicSession = async (): Promise<BasicSessionData> => {
I guess just good CSP on the server

2024-03-18 17:56 UTC, merged